app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    resource: "routing_api.yml"
    type: rest

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc